const LECTURE_CATALOG = [
  {
    title:
      'JavaScript Complete Course - Beginners to Advanced | Course Introduction',
    videoId: 'qz3dH9RdvoM',
    duration: 123,
  },
  {
    title: 'Complete JavaScript Course | Full Course Curriculum & Roadmap',
    videoId: 'RJHAunZqiwQ',
    duration: 595,
  },
  { title: 'What is JavaScript?', videoId: 'dzmxSZveph4', duration: 68 },
  { title: 'History of JavaScript', videoId: 'qikU_8uqOBI', duration: 152 },
  { title: 'Where does JavaScript run', videoId: '0vVQsL4K6X4', duration: 68 },
  { title: 'What can JavaScript do', videoId: 'XzsE04-LWxM', duration: 80 },
  { title: 'Fun facts about JavaScript', videoId: 'bHYvrnxYiYE', duration: 46 },
  {
    title: 'Using JavaScript in Browser Console',
    videoId: 'SdKJNoMSHN8',
    duration: 126,
  },
  { title: 'Setup VS Code Editor', videoId: 'fIhJajZkbeo', duration: 385 },
  { title: 'Variables in JavaScript', videoId: 'hDkFX4vLr6A', duration: 881 },
  {
    title: 'Built in Types in JavaScript',
    videoId: 'lIuEZQ9ubA0',
    duration: 969,
  },
  { title: 'Arrays in JavaScript', videoId: 'pNntv4HDc_I', duration: 676 },
  {
    title: 'Comments, Semicolons, and Best Practices',
    videoId: 'QG2c2qcsuag',
    duration: 229,
  },
  {
    title: 'Run JavaScript Code in Browser & VS Code',
    videoId: 'cL3Njth9Zlk',
    duration: 576,
  },
  {
    title: 'JavaScript Practice problems',
    videoId: 'FmaBhPfe3PA',
    duration: 461,
  },
  { title: 'Advantages of JavaScript', videoId: '25L3pQ1ZsSM', duration: 137 },
  {
    title: 'Disadvantages of JavaScript',
    videoId: 'NY8P83YLfKY',
    duration: 311,
  },
  { title: 'Operators in JavaScript', videoId: 'YBIkxR7VxrI', duration: 1147 },
  {
    title: 'Increment, Decrement Operators in JavaScript',
    videoId: 'vzkklVcX3fI',
    duration: 1156,
  },
  {
    title:
      'Conditional Statements in JavaScript - if else, switch, ternary operator',
    videoId: 'hA31ZBnIejE',
    duration: 1472,
  },
  {
    title: 'Loops in JavaScript - for, while, do while, for in, for of loops',
    videoId: 'XLgWa9_FqdM',
    duration: 1416,
  },
  {
    title: 'Practical examples of loops',
    videoId: 'DfZUcTeOq2Q',
    duration: 494,
  },
  {
    title: 'Error Handling try, catch, finally',
    videoId: '1ORkxptLsiM',
    duration: 668,
  },
  { title: 'Solve Practice Problems', videoId: 'e08hgYCAynA', duration: 307 },
  {
    title:
      'Function declaration & expressions with Parameter and empty functions',
    videoId: 'wDHT9f0hxLA',
    duration: 487,
  },
  { title: 'Arrow functions', videoId: 'EAcgZPXzpak', duration: 124 },
  {
    title: 'Default Parameters in Functions',
    videoId: 'bEXdJ2Rmxkk',
    duration: 95,
  },
  {
    title: 'Higher order functions & callbacks',
    videoId: 'Zv39VDeqIZo',
    duration: 403,
  },
  { title: 'Scope, Closures, and IIFE', videoId: 'qnuArBqhNYs', duration: 491 },
  { title: 'Currying', videoId: 'HLa14gjQxhc', duration: 89 },
  { title: 'Practice Problems', videoId: 'LXEIqDrlkN8', duration: 267 },
  { title: 'Objects', videoId: 'SodS-ZN07oM', duration: 497 },
  { title: 'Arrays', videoId: 'DBojmuc8WSw', duration: 689 },
  {
    title: 'Object & Array Destructuring',
    videoId: 'ttKdWmyNB8o',
    duration: 361,
  },
  { title: 'Spread Operators', videoId: '9uFgKqzZUN4', duration: 616 },
  { title: 'Rest Operators', videoId: 'xqpBHM7VC0U', duration: 215 },
  { title: 'Practice Problems', videoId: 'f-k_f5QP2Y4', duration: 235 },
  { title: 'What is Async JavaScript?', videoId: '1Ak4wEf0GwA', duration: 86 },
  {
    title: 'Synchronous vs Asynchronous',
    videoId: 'TA-1U-rzeec',
    duration: 284,
  },
  { title: 'Callbacks', videoId: 'oAYCX7NnKMM', duration: 628 },
  { title: 'Promises', videoId: 'Yy9ApInazlk', duration: 933 },
  { title: 'async await', videoId: 'qe0dmd6tAfg', duration: 1291 },
  { title: 'What is API?', videoId: 'Idl5yuO3BJI', duration: 924 },
  { title: 'Fetch for APIs', videoId: 'H7zCtA1YjH8', duration: 2249 },
  {
    title: 'AJAX with XMLHttpRequest & axios for APIs',
    videoId: 'Vi7f-XgCR9o',
    duration: 374,
  },
  {
    title: 'DOM Element Selection Methods',
    videoId: 'j5gXNMfTNnI',
    duration: 1124,
  },
  {
    title: 'Modifying, Add, Remove Elements',
    videoId: 'AiAeHGvE5yY',
    duration: 1120,
  },
  { title: 'Event Handling', videoId: 'BNE4TZz0D8Q', duration: 695 },
  { title: 'Event Delegation', videoId: 'L6Ws2zp2e58', duration: 256 },
  {
    title: 'Form Handling Form & Real time Validation, Input Processing',
    videoId: 'xrRZkZ_oNKs',
    duration: 1083,
  },
  { title: 'Basic ES6+ features', videoId: '9LYvbDg574Y', duration: 379 },
  { title: 'Modules', videoId: 'NyS00rMrqtM', duration: 287 },
  { title: 'Symbols', videoId: 'S8E5j4ZF3XY', duration: 367 },
  { title: 'Maps & Sets', videoId: 't9rnF0dXEOA', duration: 740 },
  { title: 'Special features', videoId: 'BmeKY2VmB60', duration: 1092 },
  { title: 'What is OOP with examples', videoId: 'e1xEKctRd9Q', duration: 155 },
  { title: 'Why use OOP', videoId: 'PXPWzQR0reA', duration: 127 },
  {
    title: 'Classes & Objects with examples',
    videoId: '8s8dVMmUCjc',
    duration: 720,
  },
  { title: 'Encapsulation', videoId: 'gPIYUgbFhBw', duration: 398 },
  { title: 'Inheritance', videoId: '2bZvS_LpCGw', duration: 182 },
  { title: 'Polymorphism', videoId: 'mk5WzX-YUjk', duration: 210 },
  { title: 'Abstraction', videoId: 'ArSmze-dMxE', duration: 785 },
  { title: 'Practice Problems', videoId: 'R-_uQyrBn-I', duration: 790 },
  { title: 'Debugging using console', videoId: 'b4s8jKhqsq4', duration: 471 },
  {
    title: 'Debugger Statement Debugging',
    videoId: 'BlRJlfnnIsU',
    duration: 206,
  },
  {
    title: 'Browser Developer Tools Debugging',
    videoId: 'EaWshCymMag',
    duration: 361,
  },
  {
    title: 'What is Web Storage Its uses & localStorage vs sessionStorage',
    videoId: 'oXVTkkEAF-s',
    duration: 301,
  },
  { title: 'localStorage with CRUD', videoId: 'RbUcD3RO5mU', duration: 648 },
  { title: 'sessionStorage with CRUD', videoId: '2Jm74THi-ns', duration: 540 },
  {
    title: 'Theme Switcher Practice Problem 1',
    videoId: 'fioOXjLSfPQ',
    duration: 780,
  },
  {
    title: 'Shopping Cart Practice Problem 2',
    videoId: '-MSmqMaXBns',
    duration: 1349,
  },
  {
    title: 'Network Status Checker App',
    videoId: 'vBlfV-hX2R4',
    duration: 1004,
  },
  {
    title: 'Location-Based Weather App',
    videoId: 'Jr1Tz-U8fC4',
    duration: 1359,
  },
  {
    title: 'Why Optimize JavaScript Performance and Optimization',
    videoId: 'V9uX8qYLero',
    duration: 164,
  },
  {
    title: 'Prevent Memory leaks in Memory Management',
    videoId: '8UzHC2Jf5Vs',
    duration: 349,
  },
  { title: 'Event Loop & Concurrency', videoId: 'E4AVLvifEnM', duration: 1308 },
  { title: 'Performance profiling', videoId: 'sVqqUY74JKg', duration: 620 },
  {
    title: 'Code Optimization Techniques',
    videoId: 'Xu-jJeTzHYM',
    duration: 150,
  },
  { title: 'Memoization', videoId: 'gEywaVvlenU', duration: 462 },
  {
    title: 'Efficient Algorithmic Approaches',
    videoId: 'FSzB4ZH8jv8',
    duration: 631,
  },
  {
    title: 'Interview Based Questions',
    videoId: 'A75JBZ9_xb0',
    duration: 2088,
  },
];

const SECTION_DEFINITIONS = [
  {
    id: 'javascript-section-1',
    title: 'Course Orientation',
    order: 1,
    start: 1,
    end: 2,
  },
  {
    id: 'javascript-section-2',
    title: 'JavaScript Foundations',
    order: 2,
    start: 3,
    end: 9,
  },
  {
    id: 'javascript-section-3',
    title: 'Variables, Types & Core Syntax',
    order: 3,
    start: 10,
    end: 17,
  },
  {
    id: 'javascript-section-4',
    title: 'Operators, Conditions & Error Handling',
    order: 4,
    start: 18,
    end: 24,
  },
  {
    id: 'javascript-section-5',
    title: 'Functions, Scope & Functional Patterns',
    order: 5,
    start: 25,
    end: 31,
  },
  {
    id: 'javascript-section-6',
    title: 'Objects, Arrays & Modern Syntax',
    order: 6,
    start: 32,
    end: 37,
  },
  {
    id: 'javascript-section-7',
    title: 'Asynchronous JavaScript & APIs',
    order: 7,
    start: 38,
    end: 45,
  },
  {
    id: 'javascript-section-8',
    title: 'DOM, Events & Forms',
    order: 8,
    start: 46,
    end: 50,
  },
  {
    id: 'javascript-section-9',
    title: 'Modern JavaScript Features',
    order: 9,
    start: 51,
    end: 55,
  },
  {
    id: 'javascript-section-10',
    title: 'Object-Oriented JavaScript',
    order: 10,
    start: 56,
    end: 63,
  },
  {
    id: 'javascript-section-11',
    title: 'Debugging & Web Storage',
    order: 11,
    start: 64,
    end: 69,
  },
  {
    id: 'javascript-section-12',
    title: 'Projects & Performance',
    order: 12,
    start: 70,
    end: 81,
  },
];

export const JAVASCRIPT_COURSE = {
  id: 'course-javascript-2026',
  slug: 'complete-javascript-course',
  title:
    'Complete JavaScript Course | Beginner to Advanced JavaScript with Projects',
  subtitle:
    'Learn JavaScript from absolute beginner to advanced with practical examples, browser APIs, DOM projects, and performance techniques.',
  description:
    'A complete JavaScript learning path from absolute beginner to advanced concepts. Follow a structured roadmap through core syntax, functions, objects, asynchronous JavaScript, APIs, the DOM, modern language features, object-oriented programming, debugging, browser storage, real-world projects, and performance optimization.',
  thumbnail: '/assets/course-javascript.png',
  price: 2999,
  isFree: false,
  currency: 'INR',
  level: 'Beginner to Advanced',
  // New imports begin as drafts. Publishing remains an explicit admin action.
  isPublished: false,
  modules: SECTION_DEFINITIONS.map((section) => ({
    id: section.id,
    title: section.title,
    order: section.order,
    lessons: LECTURE_CATALOG.slice(section.start - 1, section.end).map(
      (lecture, index) => {
        const order = section.start + index;
        return {
          id: `javascript-lesson-${String(order).padStart(2, '0')}`,
          title: `${order}. ${lecture.title}`,
          duration: lecture.duration,
          order,
          isFreePreview: order === 1,
          videoAssetRef: `youtube:${lecture.videoId}`,
        };
      },
    ),
  })),
};
